### PR TITLE
LPS-52731 move to macrodefs and merge into the jar task (on the osgi side)

### PR DESCRIPTION
**Pull request by rotty3000**
this one is doubling up the defines

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
I've made a small updated and rebased. Please update.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Another update to not break the build of other modules and to again move the config.json to `META-INF/config.json` inside the OSGi bundle.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
another update with several fixes

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-plugins/pull/340. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
